# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- redesignStructure

pool:
  vmImage: 'win1803'

pr:
- master
- releases/*

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '.\.build.ps1 -ResolveDependency'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '.\BuildOutput\testResults\unit\NUnitXml\Unit_PSv6.2_*.xml'
  condition: always()
