# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- redesignStructure

pool:
  vmImage: 'ubuntu-latest'

pr:
- master
- releases/*

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Install-Module -Name Pester,BuildHelpers,PSDeploy -Force -SkipPublisherCheck -AllowClobber -Scope CurrentUser'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '.\.build.ps1 -ResolveDependency'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/**/*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/BuildOutput/testResults'
  condition: always()
