client: Condicio
tenantDomain: condicio.nl
configPolicies:
 - bitlocker
 - corporateBranding:
   - desktopImageUrl: "https://condicio.nl/condicio.png"
   - lockscreenImageUrl: "https://condicio.nl/condicio.png"
 - deviceRestrictions:
   - homepageUrl: "https://condicio.nl"
 - endpointProtection:
   - corporateMsgTitle: "Welcome to Contoso!"
   - corporateMsgText: "Enter at your own risk..."
compliancePolicies:
 - bitlocker
scripts:
 - bitlocker
 - onedrive
 - wallpaperFix
